### ISSUE TITLE
Stuck in "executing bot"

### ISSUE THREAD

**Issue by ap0l0** [fpedrolucas95/Instagram-Bot#2]
Hi @fpedrolucas95 

The script stays in "executing bot", but the console doesn't show anything. 
I received an email saying there was a new login from a new device but nothing else.

Can you add to the console logs of what the script is doing?

<img width="867" alt="image" src="https://github.com/fpedrolucas95/Instagram-Bot/assets/14894967/15befc80-0c97-4fab-802c-b980ac6906bf">

**Comment by ap0l0** [comment]
I just saw you have a different window for the log:

<img width="712" alt="image" src="https://github.com/fpedrolucas95/Instagram-Bot/assets/14894967/28d06e83-d611-435c-b942-4a550d7fa94c">

Sorry , that's not my language. I thought "Exibir Log" meant "Exit App" haha 

Maybe you can show that log windows automatically and let the user close it?

**Comment by fpedrolucas95** [comment]
Hi @ap0l0

Thank you for using my bot, and I really appreciate your valuable feedback. Based on your input, I've made some improvements to enhance the user experience. First, I've created a branch with the application fully translated into English, which you can check out here: https://github.com/fpedrolucas95/Instagram-Bot/tree/en-us.

Additionally, I've addressed the issue you mentioned. Now, when you start the bot, the log window will be displayed automatically. These improvements were made with your feedback in mind, and I'm grateful for your input.

I hope these changes improve your experience with the bot. If you have any more suggestions or encounter any other issues, please feel free to let me know.

**Comment by ap0l0** [comment]
Thank you!!
