### ISSUE TITLE
Add "Liked" post link to log

### ISSUE THREAD

**Issue by ap0l0** [fpedrolucas95/Instagram-Bot#4]
It will be great if you can add the direct url link to the post that was liked. 

```
Taxa de engajamento do usuário erikdavid_lifestyle é de 0%, e sua última postagem foi em 30/11/2023
Liked post: https://instagram.com/blablabla
Curtiu a publicação de erikdavid_lifestyle.
```

**Comment by fpedrolucas95** [comment]
Hi @ap0l0,

Great news! We've implemented the improvement you mentioned. Now, you can give it another try. We also made some adjustments for Windows compatibility by downgrading PyQt6 to PyQt5, so please ensure you have it installed. Our requirements have been updated accordingly.

Feel free to test it out, and if you encounter any more issues or have any further feedback, don't hesitate to let us know. Your input is highly appreciated!

![image](https://github.com/fpedrolucas95/Instagram-Bot/assets/73343509/a29af06a-2ec8-44ae-910a-32dcab8d58e6)

**Comment by ap0l0** [comment]
Beautiful work @fpedrolucas95
