### ISSUE TITLE
[Feature Request] Like Last Story

### ISSUE THREAD

**Issue by ap0l0** [fpedrolucas95/Instagram-Bot#5]
Hello @fpedrolucas95 

The script now likes the last post of a user. Can you also make it to like the last story?

Open User
Like Last Post
Check if user has Stories
Like Last Story
Go to next user and repeat process

**Comment by fpedrolucas95** [comment]
Done! 
![image](https://github.com/fpedrolucas95/Instagram-Bot/assets/73343509/c8dd2447-afd1-43c1-9cd2-dd80b266264b)

**Comment by ap0l0** [comment]
you are a beast! great job, instead of the first story can you like the last story posted? The engagement is better that way, sorry I wasn't clear enough on the initial ticket.

**Comment by ap0l0** [comment]
In the meantime, I modified the script with a quick change, not sure if is a good solution but seems to be working:

From:
`primeiro_story = stories[0]
`
To
`primeiro_story = stories[-1]
`
Seems to be working
